class Book
  attr_reader :title

  def initialize(title)
    @title = title
  end
end

book = Book.new("The Great Gatsby")

puts "Title: #{book.title}"  # Reading the value using the generated getter method
# book.title = "New Title"  # This would result in an error because there's no setter method

class Car
  attr_writer :color

  def initialize(color)
    @color = color
  end
end

car = Car.new("Blue")
p car
# car.color  # This would result in an error because there's no getter method
p car.color = "Red"  # Writing the value using the generated setter method
# p car.color

class Person
  attr_accessor :name, :age
  def initialize(name, age)
    @name = name
    @age = age
  end
end

person = Person.new("Masum", 30)
puts person.name  # Calls the getter method generated by attr_accessor
puts person.age   # Calls the getter method generated by attr_accessor

person.name = "Bob"  # Calls the setter method generated by attr_accessor
person.age = 25     # Calls the setter method generated by attr_accessor

puts person.name
puts person.age


